### ISSUE TITLE
wp-cli-pre-ssh.php causes warning with wp cli 2.2.0 making db dump invalid

### ISSUE THREAD

**Issue by toffebjorkskog** [generoi/genero-conf#1]
WP cli 2.2.0 issues warning if WP_CLI_SSH_PRE_CMD is in use.
That results in extra content in the beginning of db dump files using `robo db:pull @staging`
https://github.com/wp-cli/wp-cli/pull/5197

**Comment by oxyc** [comment]
Fixed in https://github.com/generoi/robo-genero/commit/d6f8cc83ecfd6cfaa9c3294044f7fda2ce223086
